name: pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**.py"
      - ".github/**"
      - "pyproject.toml"
      - "requirements*"

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.12]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Import package
        run: |
          python -c "import sys, rocketserializer; print(f'{rocketserializer.__name__} running on Python {sys.version}')"
      - name: Install dev dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run unit tests
        run: |
          pytest -k "unit"
      - name: Run integration tests
        run: |
          pytest -k "integration"
      - name: Run acceptance tests
        run: |
          pytest -k "acceptance"
